# This file was generated by GoReleaser. DO NOT EDIT.
cask "golang-example" do
  name "golang-example"
  desc ""
  homepage ""
  version "0.6.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golang-example"

  on_macos do
    on_arm do
      url "https://github.com/attachmentgenie/golang-example/releases/download/v#{version}/golang-example_#{version}_darwin_arm64.zip",
        verified: "github.com/attachmentgenie/golang-example""
      sha256 "8537eeac895a7fd8d2d0aa2d6334b62767384095c379ecf79cad4d4ea3c1c9c3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/golang-example"]
    end
  end

  # No zap stanza required
end
