# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atc < Formula
  desc ""
  homepage ""
  version "0.0.3"
  depends_on :macos

  on_intel do
    url "https://github.com/attachmentgenie/atc/releases/download/v0.0.3/atc_0.0.3_darwin_amd64.zip"
    sha256 "8354d1a81daed98fffed6c0c228e02190a27e3ab5be33782d9eeabc1b51b6e65"

    def install
      bin.install "atc"
    end
  end
  on_arm do
    url "https://github.com/attachmentgenie/atc/releases/download/v0.0.3/atc_0.0.3_darwin_arm64.zip"
    sha256 "ec86e044285014c014590fddf68a8c783da4c9159bfda2b4c0fd2fa40ebf89b7"

    def install
      bin.install "atc"
    end
  end
end
