# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atc < Formula
  desc ""
  homepage ""
  version "0.0.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/attachmentgenie/atc/releases/download/v0.0.1/atc_0.0.1_darwin_amd64.zip"
    sha256 "eb36f35df7d6279817540172c1a140a78fcaafc23a13e3a22ade2451f328021c"

    def install
      bin.install "atc"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/attachmentgenie/atc/releases/download/v0.0.1/atc_0.0.1_darwin_arm64.zip"
    sha256 "5e4e165aeafb8d6da759abfa7c38304ae1aa060b091b36e79b2ecde3c070c389"

    def install
      bin.install "atc"
    end
  end
end
