# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example < Formula
  desc ""
  homepage ""
  version "0.3.1"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/attachmentgenie/golang-example/releases/download/v0.3.1/example_0.3.1_darwin_arm64.zip"
    sha256 "625359ce1015234b40ebb59d6d37fcbbd1a56f44ea75d9c7d6629f695b196bca"

    def install
      bin.install "example"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/attachmentgenie/golang-example/releases/download/v0.3.1/example_0.3.1_darwin_amd64.zip"
    sha256 "15593100b9b873068f5129d6c47f68bbc4f8ef899ccea667437b4c6e31ebc387"

    def install
      bin.install "example"
    end
  end
end
