# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubProjects < Formula
  desc ""
  homepage ""
  version "0.10.0"
  depends_on :macos

  on_intel do
    url "https://github.com/attachmentgenie/github-projects/releases/download/v0.10.0/github-projects_0.10.0_darwin_amd64.zip"
    sha256 "6f4c20429677e63bedfc669e69e8c0fbe9710c09a6d2f6b152f4aae1bb1ea7ae"

    def install
      bin.install "github-projects"
    end
  end
  on_arm do
    url "https://github.com/attachmentgenie/github-projects/releases/download/v0.10.0/github-projects_0.10.0_darwin_arm64.zip"
    sha256 "bb735e2d0f2ab32e79fa8bb367015731b60631ea25e32d9160ae358fe974cbf0"

    def install
      bin.install "github-projects"
    end
  end
end
