# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubProjects < Formula
  desc ""
  homepage ""
  version "0.9.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/attachmentgenie/github-projects/releases/download/v0.9.1/github-projects_0.9.1_darwin_amd64.zip"
    sha256 "280c9133ff506dc36e64590bbc281a40c09d015174db14c2374f2b67f7de1f50"

    def install
      bin.install "github-projects"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/attachmentgenie/github-projects/releases/download/v0.9.1/github-projects_0.9.1_darwin_arm64.zip"
    sha256 "2c5269d376567064f6ced49ead499a143f734413882af317e725fd82159b09e7"

    def install
      bin.install "github-projects"
    end
  end
end
