# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomadEventsSink < Formula
  desc ""
  homepage ""
  version "0.1.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/attachmentgenie/nomad-events-sink/releases/download/v0.1.1/nomad-events-sink_0.1.1_darwin_arm64.zip"
      sha256 "ee0f387d9edaf87a5891e3fa727712d0aa63a4a7cb85a428bce7d85b1ed44cac"

      def install
        bin.install "nomad-events-sink"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/attachmentgenie/nomad-events-sink/releases/download/v0.1.1/nomad-events-sink_0.1.1_darwin_amd64.zip"
      sha256 "f7aa76c30a9fd0f4977773c72a58bd6552cef00e7d0c77432639c19e530dd427"

      def install
        bin.install "nomad-events-sink"
      end
    end
  end
end
