# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomadLogger < Formula
  desc ""
  homepage ""
  version "0.5.0"
  depends_on :macos

  on_intel do
    url "https://github.com/attachmentgenie/nomad-logger/releases/download/v0.5.0/nomad-logger_0.5.0_darwin_amd64.zip"
    sha256 "5bda73bd437b6cf3ec213efb993ed1a313ab91d263a37905828c039d21b3a447"

    def install
      bin.install "nomad-logger"
    end
  end
  on_arm do
    url "https://github.com/attachmentgenie/nomad-logger/releases/download/v0.5.0/nomad-logger_0.5.0_darwin_arm64.zip"
    sha256 "88d3d93f2c0e0a8219f53394312a2ff873866216574c6302891216eb751f7acd"

    def install
      bin.install "nomad-logger"
    end
  end
end
