# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomadLogger < Formula
  desc ""
  homepage ""
  version "0.4.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/attachmentgenie/nomad-logger/releases/download/v0.4.1/nomad-logger_0.4.1_darwin_amd64.zip"
    sha256 "8a3f7de4e545cb18df154cf2e4d2a4c8f087d2ec85d1faf6dc6821c8de24a412"

    def install
      bin.install "nomad-logger"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/attachmentgenie/nomad-logger/releases/download/v0.4.1/nomad-logger_0.4.1_darwin_arm64.zip"
    sha256 "108c7802c0a3e3cc4b73759ceb83e642b53b47665e8beb1bec4c6a34497f58eb"

    def install
      bin.install "nomad-logger"
    end
  end
end
