# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomadEventsSink < Formula
  desc ""
  homepage ""
  version "0.2.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/attachmentgenie/nomad-events-sink/releases/download/v0.2.1/nomad-events-sink_0.2.1_darwin_arm64.zip"
      sha256 "4f4676fc3da1c3097daf8d4b9c4702ee9df1b9d127a5a5a7afe25b9d4d022581"

      def install
        bin.install "nomad-events-sink"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/attachmentgenie/nomad-events-sink/releases/download/v0.2.1/nomad-events-sink_0.2.1_darwin_amd64.zip"
      sha256 "899a4bb17fb74b26905d4a6efd9795e6bd078aa2003c07bdfb65d56496f25bac"

      def install
        bin.install "nomad-events-sink"
      end
    end
  end
end
