# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PuppetDynamodbOtp < Formula
  desc ""
  homepage ""
  version "0.1.3"
  depends_on :macos

  on_intel do
    url "https://github.com/attachmentgenie/puppet-dynamodb-otp/releases/download/v0.1.3/puppet-dynamodb-otp_0.1.3_darwin_amd64.zip"
    sha256 "4180f2f606796bfc869dd4e0a1341300e9b104d8bb1f9b15b4bd82b054526d67"

    def install
      bin.install "puppet-dynamodb-otp"
    end
  end
  on_arm do
    url "https://github.com/attachmentgenie/puppet-dynamodb-otp/releases/download/v0.1.3/puppet-dynamodb-otp_0.1.3_darwin_arm64.zip"
    sha256 "9bdc51fd04b35d5359872e3cb3dae58ac5781fb180e98f156d39525ba5e7ee84"

    def install
      bin.install "puppet-dynamodb-otp"
    end
  end
end
