# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PuppetDynamodbOtp < Formula
  desc ""
  homepage ""
  version "0.1.2"
  depends_on :macos

  on_intel do
    url "https://github.com/attachmentgenie/puppet-dynamodb-otp/releases/download/v0.1.2/puppet-dynamodb-otp_0.1.2_darwin_amd64.zip"
    sha256 "9ae414a608fcdacd562307b7c289e9e5b301cfdfd6c5bb2c0d56ce541e44c7e4"

    def install
      bin.install "puppet-dynamodb-otp"
    end
  end
  on_arm do
    url "https://github.com/attachmentgenie/puppet-dynamodb-otp/releases/download/v0.1.2/puppet-dynamodb-otp_0.1.2_darwin_arm64.zip"
    sha256 "464e3f91b3921694186da9c072bdfff948ad694db4c0910cc4f995eb1beecae3"

    def install
      bin.install "puppet-dynamodb-otp"
    end
  end
end
